# Generated by Django 3.1.7 on 2021-03-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200516_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nxt_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_post', to='posts.post', verbose_name='Next Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='prev_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_post', to='posts.post', verbose_name='Previous Post'),
        ),
    ]
